[build]
  functions = "functions"
  command = "npm install"

[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
