[build]
  command = "npm run build"
  publish = "frontend/dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api-docs"
  to = "/.netlify/functions/api/api-docs"
  status = 200

[[redirects]]
  from = "/person/docs"
  to = "/.netlify/functions/person/docs"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/swagger"
  status = 200

[[redirects]]
  from = "/swagger"
  to = "/.netlify/functions/swagger"
  status = 200

[[redirects]]
  from = "/swagger-simple"
  to = "/.netlify/functions/swagger-simple"
  status = 200

[[redirects]]
  from = "/swagger.html"
  to = "/swagger.html"
  status = 200

[[redirects]]
  from = "/api-spec.json"
  to = "/api-spec.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
